apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::533267327230:role/employee-portal-build-role
      username: codebuild
      groups:
        - system:masters